# 导入包

In [2]:

import torch
import numpy

## torch中常用的创建张量的方法

In [2]:
#创建一个tensor
a = torch.tensor([[1,2,3],[4,5,6]])
#获得张量a的形状，是一个元组
print(a.size())
print(a)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:

x = torch.empty(2, 3)
print(x.size())
#多次运行可以看到，每次的x都是不一样的，因为未初始化
print(x)

torch.Size([2, 3])
tensor([[6.6280e-10, 6.5920e-10, 2.6082e+20],
        [1.0721e-08, 5.2299e+22, 6.7945e-07]])


In [6]:
#运用a参数后，此时y和a一样了
y = torch.empty(2,3,out = a)
print(y.size())
print(y)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [8]:
#创建一个size和y一样的未初始化张量
empty_like = torch.empty_like(y)
print(empty_like.size())
print(empty_like)

torch.Size([2, 3])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [9]:
# 创建一个随机的初始化矩阵
x = torch.rand(2,3)
print(x)

tensor([[0.0559, 0.8401, 0.7197],
        [0.7270, 0.6326, 0.8509]])


- torch.rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    - 返回服从均匀分布的初始化后的张量，张量大小由参数size定义。
    - 参数说明：
        size(int…)：是一个用于定义输出的张量的形状的整形序列，也可以是list或者tuple。
        out(Tensor，可选)：要求的值为张量，默认为none。也可以令out为一个具体张量a（a的shape与参数size相同），这样输出的张量就会和a一样。
        dtype(torch.dtype，可选): 要求的值的类型是torch.dtype，默认值是torch.set_default_tensor_type的值。可以通过这个dtype参数来改变输出的张量的数据类型。
        layout(torch.layout，可选)：torch.layput表示torch.Tensor内存布局的对象。这个参数表示你希望返回的张量的内存布局类型，默认为torch.strided。torch.strided代表密集型张量，是最常见的内存布局；每个strided张量都关联一个torch.Storage，torch.Storage保存着strided张量的数据。
        device(torch.device,可选):创建的张量存放的device。
        requires_grad(bool，可选)：要求的值为bool类型，默认为False。若为False则反向传播时不会对这个节点求导。

In [10]:
# 创建一个全是0的矩阵，并且令数据类型为torch.long
x = torch.zeros(2,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]])


- torch.zeros(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    - 返回一个值全为0的张量，张量大小由参数size定义，值类型由torch.dtype定义。
    - 参数说明：
        size(int…)：是一个用于定义输出的张量的形状的整形序列，也可以是list或者tuple。
        out(Tensor，可选)：要求的值为张量，默认为none。也可以令out为一个具体张量a（a的shape与参数size相同），这样输出的张量就会和a一样。
        dtype(torch.dtype，可选): 要求的值的类型是torch.dtype，默认值是torch.set_default_tensor_type的值。可以通过这个dtype参数来改变输出的张量的数据类型。
        layout(torch.layout，可选)：torch.layput表示torch.Tensor内存布局的对象。这个参数表示你希望返回的张量的内存布局类型，默认为torch.strided。torch.strided代表密集型张量，是最常见的内存布局；每个strided张量都关联一个torch.Storage，torch.Storage保存着strided张量的数据。
        device(torch.device,可选):创建的张量存放的device。
        requires_grad(bool，可选)：要求的值为bool类型，默认为False。若为False则反向传播时不会对这个节点求导。
        '''

In [11]:
# 创建一个全是1的张量，并在此基础上创建新的张量
#创建一个全是1的矩阵
x = x.new_ones(2,3,dtype = torch.double)
print(x)
#重新设定了dtype
x = torch.rand_like(x,dtype = torch.float)
#可以看到形状一样，但数据类型不同了。
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.6288, 0.0157, 0.2382],
        [0.2832, 0.6589, 0.8351]])


In [13]:
x = torch.tensor((),dtype = torch.int32)
print(x)
x = x.new_ones(2,3)
print(x)

tensor([], dtype=torch.int32)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


- new_ones(size, dtype=None, device=None, requires_grad=False) -> Tensor
    - 返回一个值全为1的张量，张量的size和dtype与tensor相同。
    - 参数说明：
        size(int…)：是一个用于定义输出的张量的形状的整形序列，也可以是list或者tuple。
        dtype(torch.dtype，可选): 要求的值的类型是torch.dtype，默认值是None。若为None，则为与tensor相同的torch.dtype。
        device(torch.device,可选):创建的张量存放的device，默认与input相同。
        requires_grad(bool，可选)：要求的值为bool类型，默认为False。若为False则反向传播时不会对这个节点求导。
        '''
- torch.randn_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format) -> Tensor
    - 返回一个和input相同size的张量，这个张量由均值为0，方差为1的标准正态分布填充。
    - 参数说明：
        dtype(torch.dtype，可选): 要求的值的类型是torch.dtype，默认值是None。若为None，则为与input相同的torch.dtype。
        layout(torch.layout，可选)：torch.layput表示torch.Tensor内存布局的对象。这个参数表示你希望返回的张量的内存布局类型，默认为input的分布。
        device(torch.device, 可选):创建的张量存放的device,默认与input相同。
        requires_grad(bool，可选)：要求的值为bool类型，默认为False。若为False则反向传播时不会对这个节点求导。
        memory_format(torch.memory_format, 可选): 期望返回张量的保存类型，默认为torch.preserve_format。torch.memory类型用于保存torch.Tensor的储存格式。torch.preserve_format是保留输入张量的内存格式，用在clone这样的函数中。如果输入张量是分配在稠密不重叠的内存中，那么输出张量的stride与输入相同。否则，输出的strides使用torch.contiguous_format。


In [14]:
# 创建一个值全为3.1416的5*3的矩阵
x=torch.full((5, 3), 3.1416)
print(x)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])


- torch.full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor
    - 返回一个未初始化的张量，张量大小由参数size定义。
    - 参数说明：
        size(int…)：是一个用于定义输出的张量的形状的整形序列，也可以是list或者turple。
        out(Tensor，可选)：要求的值为张量，默认为none。也可以令out为一个具体张量a（a的shape与参数size相同），这样输出的张量就会和a一样。上面的例子可以看出。
        dtype(torch.dtype，可选): 要求的值的类型是torch.dtype，默认值是torch.set_default_tensor_type的值。可以通过这个dtype参数来改变输出的张量的数据类型。
        layout(torch.layout，可选)：torch.layput表示torch.Tensor内存布局的对象。这个参数表示你希望返回的张量的内存布局类型，默认为torch.strided。torch.strided代表密集型张量，是最常见的内存布局；每个strided张量都关联一个torch.Storage，torch.Storage保存着strided张量的数据。
        device(torch.device,可选):创建的张量存放的device。
        requires_grad(bool，可选)：要求的值为bool类型，默认为False。若为False则反向传播时不会对这个节点求导。


In [15]:
# 创建一个维度为4，对角线位置为1，其他位置全为0的二维张量。
eye = torch.eye(4)
print(eye.size())#获得张量eye的形状，是一个元组
print(eye)

torch.Size([4, 4])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


- torch.eye(n, m=None, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
    - 返回一个行数为n，列数为m，对角线上为1而其他位置为0的二维张量。
    - 参数说明：
        n(int):要求输入一个整数，表示行数。
        m(int):要求输入一个整数，表示列数，默认为None。如果为None，则m的值为n。
        out(Tensor，可选)：要求的值为张量，默认为none。也可以令out为一个具体张量a（a的shape与参数size相同），这样输出的张量就会和a一样。
        dtype(torch.dtype，可选): 要求的值的类型是torch.dtype，默认值是torch.set_default_tensor_type的值。可以通过这个dtype参数来改变输出的张量的数据类型。
        layout(torch.layout，可选)：torch.layput表示torch.Tensor内存布局的对象。这个参数表示你希望返回的张量的内存布局类型，默认为torch.strided。torch.strided代表密集型张量，是最常见的内存布局；每个strided张量都关联一个torch.Storage，torch.Storage保存着strided张量的数据。
        device(torch.device,可选):创建的张量存放的device。
        requires_grad(bool，可选)：要求的值为bool类型，默认为False。若为False则反向传播时不会对这个节点求导。

## 基本运算操作

In [3]:
a = torch.rand(5,3)
b = torch.rand(5,3)
print(a)
print(b)
print(a + b)
print(torch.add(a, b))

tensor([[0.2093, 0.4807, 0.3659],
        [0.8315, 0.0009, 0.7417],
        [0.7746, 0.6414, 0.6804],
        [0.3440, 0.8610, 0.6680],
        [0.8730, 0.6988, 0.8227]])
tensor([[0.7758, 0.9211, 0.1448],
        [0.3644, 0.9201, 0.1888],
        [0.0368, 0.4946, 0.9918],
        [0.0146, 0.3755, 0.0517],
        [0.6742, 0.9276, 0.6756]])
tensor([[0.9851, 1.4018, 0.5107],
        [1.1959, 0.9210, 0.9305],
        [0.8115, 1.1360, 1.6721],
        [0.3586, 1.2365, 0.7197],
        [1.5472, 1.6263, 1.4983]])
tensor([[0.9851, 1.4018, 0.5107],
        [1.1959, 0.9210, 0.9305],
        [0.8115, 1.1360, 1.6721],
        [0.3586, 1.2365, 0.7197],
        [1.5472, 1.6263, 1.4983]])


In [4]:
result = torch.empty(5,3)
print(result)
#out参数提供一个输出张量作为加法的结果
torch.add(a, b, out = result)
print(result)

tensor([[1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39],
        [9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38]])
tensor([[0.9851, 1.4018, 0.5107],
        [1.1959, 0.9210, 0.9305],
        [0.8115, 1.1360, 1.6721],
        [0.3586, 1.2365, 0.7197],
        [1.5472, 1.6263, 1.4983]])
